"""Add new table Run

Revision ID: 96efb20c7140
Revises: 93b5458cf92c
Create Date: 2025-02-04 16:20:40.776981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96efb20c7140'
down_revision: Union[str, None] = '93b5458cf92c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('task', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('cycledata_id', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('state_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_last_activity', sa.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('disabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('time_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'task', 'dataset_name', name='unique_dataset_name')
    )
    op.add_column('model', sa.Column('run_id', sa.UUID(), nullable=True))
    op.drop_constraint('model_application_id_fkey', 'model', type_='foreignkey')
    op.create_foreign_key(None, 'model', 'run', ['run_id'], ['id'])
    op.drop_column('model', 'cycling_id')
    op.drop_column('model', 'application_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('model', sa.Column('cycling_id', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'model', type_='foreignkey')
    op.create_foreign_key('model_application_id_fkey', 'model', 'application', ['application_id'], ['id'])
    op.drop_column('model', 'run_id')
    op.drop_table('run')
    # ### end Alembic commands ###
