"""cascade_by_db

Revision ID: bca695b8dbea
Revises: d42ed21f31b4
Create Date: 2026-02-05 13:13:40.329624

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'bca695b8dbea'
down_revision: Union[str, None] = 'd42ed21f31b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('api_key_user_id_fkey'), 'api_key', type_='foreignkey')
    op.create_foreign_key(None, 'api_key', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('application_motor_id_fkey'), 'application', type_='foreignkey')
    op.create_foreign_key(None, 'application', 'motor', ['motor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('cycledata_application_id_fkey'), 'cycledata', type_='foreignkey')
    op.create_foreign_key(None, 'cycledata', 'application', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('measuringpoint_cycle_id_fkey'), 'measuringpoint', type_='foreignkey')
    op.drop_constraint(op.f('measuringpoint_application_id_fkey'), 'measuringpoint', type_='foreignkey')
    op.create_foreign_key(None, 'measuringpoint', 'cycledata', ['cycle_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'measuringpoint', 'application', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('model_run_id_fkey'), 'model', type_='foreignkey')
    op.create_foreign_key(None, 'model', 'run', ['run_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('prediction_run_id_fkey'), 'prediction', type_='foreignkey')
    op.drop_constraint(op.f('prediction_model_id_fkey'), 'prediction', type_='foreignkey')
    op.create_foreign_key(None, 'prediction', 'run', ['run_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'prediction', 'model', ['model_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('run_application_id_fkey'), 'run', type_='foreignkey')
    op.create_foreign_key(None, 'run', 'application', ['application_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'run', type_='foreignkey')
    op.create_foreign_key(op.f('run_application_id_fkey'), 'run', 'application', ['application_id'], ['id'])
    op.drop_constraint(None, 'prediction', type_='foreignkey')
    op.drop_constraint(None, 'prediction', type_='foreignkey')
    op.create_foreign_key(op.f('prediction_model_id_fkey'), 'prediction', 'model', ['model_id'], ['id'])
    op.create_foreign_key(op.f('prediction_run_id_fkey'), 'prediction', 'run', ['run_id'], ['id'])
    op.drop_constraint(None, 'model', type_='foreignkey')
    op.create_foreign_key(op.f('model_run_id_fkey'), 'model', 'run', ['run_id'], ['id'])
    op.drop_constraint(None, 'measuringpoint', type_='foreignkey')
    op.drop_constraint(None, 'measuringpoint', type_='foreignkey')
    op.create_foreign_key(op.f('measuringpoint_application_id_fkey'), 'measuringpoint', 'application', ['application_id'], ['id'])
    op.create_foreign_key(op.f('measuringpoint_cycle_id_fkey'), 'measuringpoint', 'cycledata', ['cycle_id'], ['id'])
    op.drop_constraint(None, 'cycledata', type_='foreignkey')
    op.create_foreign_key(op.f('cycledata_application_id_fkey'), 'cycledata', 'application', ['application_id'], ['id'])
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.create_foreign_key(op.f('application_motor_id_fkey'), 'application', 'motor', ['motor_id'], ['id'])
    op.drop_constraint(None, 'api_key', type_='foreignkey')
    op.create_foreign_key(op.f('api_key_user_id_fkey'), 'api_key', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
