"""Init with OperationalData

Revision ID: d2aca3e90cf3
Revises: 
Create Date: 2024-06-28 07:15:30.344116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2aca3e90cf3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('disabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('time_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', sa.String(), server_default='guest', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('motor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('serial', sa.String(), nullable=False),
    sa.Column('part', sa.String(), nullable=False),
    sa.Column('machine', sa.String(), server_default='', nullable=True),
    sa.Column('client', sa.String(), server_default='', nullable=True),
    sa.Column('disabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('time_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial', 'part', name='unique_motor')
    )
    op.create_index(op.f('ix_motor_part'), 'motor', ['part'], unique=False)
    op.create_index(op.f('ix_motor_serial'), 'motor', ['serial'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('motor_id', sa.Integer(), nullable=True),
    sa.Column('context_code', sa.String(), nullable=False),
    sa.Column('recipe', sa.String(), nullable=False),
    sa.Column('disabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('time_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['motor_id'], ['motor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('motor_id', 'context_code', 'recipe', name='unique_application')
    )
    op.create_table('cycledata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('driveConfig', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cycleConfig', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('testCycleCounter', sa.Integer(), nullable=True),
    sa.Column('disabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('time_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_onnx', sa.LargeBinary(), nullable=False),
    sa.Column('model_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cycling_id', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('disabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('time_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model')
    op.drop_table('cycledata')
    op.drop_table('application')
    op.drop_index(op.f('ix_motor_serial'), table_name='motor')
    op.drop_index(op.f('ix_motor_part'), table_name='motor')
    op.drop_table('motor')
    op.drop_table('user')
    # ### end Alembic commands ###
