"""Add measuringpoint

Revision ID: d42ed21f31b4
Revises: 55890bcc4ec2
Create Date: 2026-01-07 10:21:41.827071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42ed21f31b4'
down_revision: Union[str, None] = '55890bcc4ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Remove models without run_id
    op.execute("""
        DELETE FROM model
        WHERE run_id IS NULL;
    """)
    # Remove runs without user_id
    op.execute("""
        DELETE FROM run
        WHERE user_id IS NULL;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measuringpoint',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('application_id', sa.Integer(), nullable=False),
                    sa.Column('cycle_id', sa.Integer(), nullable=False),
                    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('act_current', sa.REAL, nullable=True),
                    sa.Column('act_following_error', sa.REAL, nullable=True),
                    sa.Column('act_position', sa.REAL, nullable=True),
                    sa.Column('act_torque', sa.REAL, nullable=True),
                    sa.Column('act_velocity', sa.REAL, nullable=True),
                    sa.Column('cmd_position', sa.REAL, nullable=True),
                    sa.Column('cmd_velocity', sa.REAL, nullable=True),
                    sa.Column('temp_motor', sa.REAL, nullable=True),
                    sa.Column('temp_power_stage', sa.REAL, nullable=True),
                    sa.Column('disabled', sa.Boolean(), server_default='false', nullable=False),
                    sa.Column('time_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
                    sa.ForeignKeyConstraint(['cycle_id'], ['cycledata.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # Set custom storage parameters
    # fillfactor = 95 --> Rare updates, but possible - leave some space
    # autovacuum_vacuum_scale_factor = 0.05 --> More frequent vacuums to keep table bloat low
    # autovacuum_analyze_scale_factor = 0.05 --> More frequent analyzes to keep statistics up-to-date
    op.execute(sa.text("""
        ALTER TABLE measuringpoint SET (
            fillfactor = 95,
            autovacuum_vacuum_scale_factor = 0.05,
            autovacuum_analyze_scale_factor = 0.05
        )
    """))

    op.create_index('idx_mp_app_ts_current', 'measuringpoint', ['application_id', 'timestamp'], unique=False,
                    postgresql_include=['cycle_id', 'act_current'], postgresql_where=sa.text('act_current IS NOT NULL'))
    op.create_index(op.f('ix_api_key_user_id'), 'api_key', ['user_id'], unique=False)
    op.alter_column('application', 'motor_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.create_index(op.f('ix_application_motor_id'), 'application', ['motor_id'], unique=False)
    op.alter_column('cycledata', 'application_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.create_index(op.f('ix_cycledata_application_id'), 'cycledata', ['application_id'], unique=False)
    op.alter_column('model', 'run_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.create_index(op.f('ix_model_run_id'), 'model', ['run_id'], unique=False)
    op.create_index(op.f('ix_prediction_model_id'), 'prediction', ['model_id'], unique=False)
    op.alter_column('run', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.create_index(op.f('ix_run_application_id'), 'run', ['application_id'], unique=False)
    op.create_index(op.f('ix_run_state'), 'run', ['state'], unique=False)
    op.create_index(op.f('ix_run_task'), 'run', ['task'], unique=False)
    op.create_index(op.f('ix_run_user_id'), 'run', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_user_id'), table_name='run')
    op.drop_index(op.f('ix_run_task'), table_name='run')
    op.drop_index(op.f('ix_run_state'), table_name='run')
    op.drop_index(op.f('ix_run_application_id'), table_name='run')
    op.alter_column('run', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_index(op.f('ix_prediction_model_id'), table_name='prediction')
    op.drop_index(op.f('ix_model_run_id'), table_name='model')
    op.alter_column('model', 'run_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.drop_index(op.f('ix_cycledata_application_id'), table_name='cycledata')
    op.alter_column('cycledata', 'application_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_index(op.f('ix_application_motor_id'), table_name='application')
    op.alter_column('application', 'motor_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_index(op.f('ix_api_key_user_id'), table_name='api_key')
    op.drop_index('idx_mp_app_ts_current', table_name='measuringpoint', postgresql_include=['cycle_id', 'act_current'], postgresql_where=sa.text('act_current IS NOT NULL'))
    op.drop_table('measuringpoint')
    # ### end Alembic commands ###
