features_dict = {
    'absolute_sum_of_changes': None,
    'agg_autocorrelation': [{'f_agg': 'mean', 'maxlag': 40},
                            {'f_agg': 'median', 'maxlag': 40},
                            {'f_agg': 'var', 'maxlag': 40}],
    'agg_linear_trend': [{'attr': 'rvalue', 'chunk_len': 5, 'f_agg': 'max'},
                         {'attr': 'intercept', 'chunk_len': 5, 'f_agg': 'max'},
                         {'attr': 'intercept', 'chunk_len': 5, 'f_agg': 'min'},
                         {'attr': 'intercept', 'chunk_len': 5, 'f_agg': 'mean'},
                         {'attr': 'intercept', 'chunk_len': 5, 'f_agg': 'var'},
                         {'attr': 'intercept', 'chunk_len': 10, 'f_agg': 'max'},
                         {'attr': 'intercept', 'chunk_len': 10, 'f_agg': 'min'},
                         {'attr': 'intercept', 'chunk_len': 10, 'f_agg': 'mean'},
                         {'attr': 'intercept', 'chunk_len': 10, 'f_agg': 'var'},
                         {'attr': 'intercept', 'chunk_len': 50, 'f_agg': 'max'},
                         {'attr': 'intercept', 'chunk_len': 50, 'f_agg': 'min'},
                         {'attr': 'intercept', 'chunk_len': 50, 'f_agg': 'mean'},
                         {'attr': 'intercept', 'chunk_len': 50, 'f_agg': 'var'},
                         {'attr': 'slope', 'chunk_len': 5, 'f_agg': 'max'},
                         {'attr': 'slope', 'chunk_len': 5, 'f_agg': 'min'},
                         {'attr': 'slope', 'chunk_len': 5, 'f_agg': 'mean'},
                         {'attr': 'slope', 'chunk_len': 5, 'f_agg': 'var'},
                         {'attr': 'slope', 'chunk_len': 10, 'f_agg': 'max'},
                         {'attr': 'slope', 'chunk_len': 10, 'f_agg': 'min'},
                         {'attr': 'slope', 'chunk_len': 10, 'f_agg': 'mean'},
                         {'attr': 'slope', 'chunk_len': 10, 'f_agg': 'var'},
                         {'attr': 'slope', 'chunk_len': 50, 'f_agg': 'max'},
                         {'attr': 'slope', 'chunk_len': 50, 'f_agg': 'min'},
                         {'attr': 'slope', 'chunk_len': 50, 'f_agg': 'mean'},
                         {'attr': 'slope', 'chunk_len': 50, 'f_agg': 'var'},
                         {'attr': 'stderr', 'chunk_len': 5, 'f_agg': 'max'},
                         {'attr': 'stderr', 'chunk_len': 5, 'f_agg': 'min'},
                         {'attr': 'stderr', 'chunk_len': 5, 'f_agg': 'mean'},
                         {'attr': 'stderr', 'chunk_len': 5, 'f_agg': 'var'},
                         {'attr': 'stderr', 'chunk_len': 10, 'f_agg': 'max'},
                         {'attr': 'stderr', 'chunk_len': 10, 'f_agg': 'min'},
                         {'attr': 'stderr', 'chunk_len': 10, 'f_agg': 'mean'},
                         {'attr': 'stderr', 'chunk_len': 10, 'f_agg': 'var'},
                         {'attr': 'stderr', 'chunk_len': 50, 'f_agg': 'max'},
                         {'attr': 'stderr', 'chunk_len': 50, 'f_agg': 'min'},
                         {'attr': 'stderr', 'chunk_len': 50, 'f_agg': 'mean'},
                         {'attr': 'stderr', 'chunk_len': 50, 'f_agg': 'var'}],
    'autocorrelation': [1, 2, 3, 4, 5, 6, 7, 8, 9],
    'binned_entropy': [10],
    'c3': [1, 2, 3],
    'change_quantiles': [
        {'ql': 0.0, 'qh': 0.6, 'isabs': False, 'f_agg': 'var'},
        {'ql': 0.0, 'qh': 0.6, 'isabs': True, 'f_agg': 'mean'},
        {'ql': 0.0, 'qh': 0.6, 'isabs': True, 'f_agg': 'var'},
        {'ql': 0.0, 'qh': 0.8, 'isabs': False, 'f_agg': 'var'},
        {'ql': 0.0, 'qh': 0.8, 'isabs': True, 'f_agg': 'mean'},
        {'ql': 0.0, 'qh': 0.8, 'isabs': True, 'f_agg': 'var'},
        {'ql': 0.0, 'qh': 1.0, 'isabs': False, 'f_agg': 'var'},
        {'ql': 0.0, 'qh': 1.0, 'isabs': True, 'f_agg': 'mean'},
        {'ql': 0.0, 'qh': 1.0, 'isabs': True, 'f_agg': 'var'},
        {'ql': 0.4, 'qh': 0.6, 'isabs': False, 'f_agg': 'var'},
        {'ql': 0.4, 'qh': 0.6, 'isabs': True, 'f_agg': 'mean'},
        {'ql': 0.4, 'qh': 0.6, 'isabs': True, 'f_agg': 'var'},
        {'ql': 0.8, 'qh': 1.0, 'isabs': False, 'f_agg': 'var'},
        {'ql': 0.8, 'qh': 1.0, 'isabs': True, 'f_agg': 'mean'},
        {'ql': 0.8, 'qh': 1.0, 'isabs': True, 'f_agg': 'var'}],
    'cid_ce': [True, False],
    'CWT': [
        "mean_power",
        "std_power",
        # "max_power",
        "argmax_scale",
        "argmax_time",
        "band_power_low",
        "band_power_high",
        "band_ratio_low",
        "band_ratio_high",
        "spectral_entropy",
        "num_peaks"],
    'cwt_coefficients': [
        {'widths': (2, 5, 10, 20), 'coeff': 3, 'w': 5},
        {'widths': (2, 5, 10, 20), 'coeff': 3, 'w': 20},
        {'widths': (2, 5, 10, 20), 'coeff': 5, 'w': 5},
        {'widths': (2, 5, 10, 20), 'coeff': 5, 'w': 20},
        {'widths': (2, 5, 10, 20), 'coeff': 6, 'w': 5},
        {'widths': (2, 5, 10, 20), 'coeff': 6, 'w': 20},
        {'widths': (2, 5, 10, 20), 'coeff': 7, 'w': 5},
        {'widths': (2, 5, 10, 20), 'coeff': 7, 'w': 20},
        {'widths': (2, 5, 10, 20), 'coeff': 8, 'w': 5},
        {'widths': (2, 5, 10, 20), 'coeff': 8, 'w': 20}],
    'energy_ratio_by_chunks': [{'num_segments': 10, 'segment_focus': i} for i in range(10)],
    'fft_aggregated': [{'aggtype': 'centroid'},
                       {'aggtype': 'variance'},
                       {'aggtype': 'skew'},
                       {'aggtype': 'kurtosis'}],
    'fft_coefficient': [{'coeff': c, 'attr': attr} for c in [17, 23, 29, 35, 43, 47, 51, 57, 64, 71, 81]
                        for attr in ['real', 'imag', 'angle']],
    'mean_second_derivative_central': None,
    'number_cwt_peaks': [1, 5],
    'number_peaks': [1, 3, 5, 10, 50],
    'partial_autocorrelation': [{'lag': i} for i in range(1, 10)],
    'percentage_of_reoccurring_values_to_all_values': None,
    'quantile': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
    'ratio_value_number_to_time_series_length': None,
    'sample_entropy': None,
    'spkt_welch_density': [{'coeff': 2}, {'coeff': 5}, {'coeff': 8}]
}
